// This file is a fallback for using MaterialIcons on Android and web.

import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { SymbolWeight } from 'expo-symbols';
import { memo } from 'react';
import { OpaqueColorValue, StyleProp, TextStyle } from 'react-native';

// Add your SFSymbol to MaterialIcons mappings here.
export type IconSymbolName = keyof typeof MAPPING;

/**
 * Add your SF Symbols to Material Icons mappings here.
 * - see Material Icons in the [Icons Directory](https://icons.expo.fyi).
 * - see SF Symbols in the [SF Symbols](https://developer.apple.com/sf-symbols/) app.
 */
const MAPPING = {
  // Navigation & Interface
  house: 'home',
  'house.fill': 'home',
  'chevron.left': 'arrow-back',
  'chevron.right': 'arrow-forward',
  'chevron.up': 'keyboard-arrow-up',
  'chevron.down': 'keyboard-arrow-down',
  'line.3.horizontal': 'menu',
  xmark: 'close',
  ellipsis: 'more-horiz',
  plus: 'add',
  'plus.circle': 'add-circle',
  'plus.circle.fill': 'add-circle',
  minus: 'remove',
  'minus.circle': 'remove-circle',
  'minus.circle.fill': 'remove-circle',
  magnifyingglass: 'search',
  checkmark: 'check',
  'checkmark.circle': 'check-circle',
  'checkmark.circle.fill': 'check-circle',
  'arrow.left': 'arrow-back',
  'arrow.right': 'arrow-forward',
  'arrow.up': 'arrow-upward',
  'arrow.down': 'arrow-downward',
  'arrow.clockwise': 'refresh',
  'arrow.counterclockwise': 'refresh',

  // Social & Communication
  paperplane: 'send',
  'paperplane.fill': 'send',
  envelope: 'email',
  'envelope.fill': 'email',
  'envelope.open': 'drafts',
  'envelope.open.fill': 'drafts',
  person: 'person',
  'person.fill': 'person',
  'person.crop.circle': 'account-circle',
  'person.crop.circle.fill': 'account-circle',
  'person.2': 'people',
  'person.2.fill': 'people',
  'person.3': 'groups',
  'person.3.fill': 'groups',
  'square.and.arrow.up': 'share',
  'square.and.arrow.down': 'download',
  phone: 'phone',
  'phone.fill': 'phone',
  'video.fill': 'videocam',
  video: 'videocam',

  // Status & Actions
  star: 'star-border',
  'star.fill': 'star',
  bookmark: 'bookmark-border',
  'bookmark.fill': 'bookmark',
  heart: 'favorite-border',
  'heart.fill': 'favorite',
  pencil: 'edit',
  'pencil.circle': 'edit',
  'pencil.circle.fill': 'edit',
  trash: 'delete',
  'trash.fill': 'delete',
  'trash.circle': 'delete',
  'trash.circle.fill': 'delete',
  eye: 'visibility',
  'eye.fill': 'visibility',
  'eye.slash': 'visibility-off',
  'eye.slash.fill': 'visibility-off',
  flag: 'flag',
  'flag.fill': 'flag',

  // Media Controls
  play: 'play-arrow',
  'play.fill': 'play-arrow',
  'play.circle': 'play-circle-outline',
  'play.circle.fill': 'play-circle-filled',
  pause: 'pause',
  'pause.fill': 'pause',
  'pause.circle': 'pause-circle-outline',
  'pause.circle.fill': 'pause-circle-filled',
  stop: 'stop',
  'stop.fill': 'stop',
  'stop.circle': 'stop-circle',
  'stop.circle.fill': 'stop-circle',
  'forward.fill': 'skip-next',
  'backward.fill': 'skip-previous',
  speaker: 'volume-up',
  'speaker.fill': 'volume-up',
  'speaker.slash': 'volume-off',
  'speaker.slash.fill': 'volume-off',
  'speaker.wave.1': 'volume-down',
  'speaker.wave.1.fill': 'volume-down',
  'speaker.wave.2': 'volume-up',
  'speaker.wave.2.fill': 'volume-up',
  'speaker.wave.3': 'volume-up',
  'speaker.wave.3.fill': 'volume-up',
  microphone: 'mic',
  'microphone.fill': 'mic',
  'microphone.slash': 'mic-off',
  'microphone.slash.fill': 'mic-off',
  headphones: 'headphones',

  // Tools & Functions
  calendar: 'calendar-today',
  'calendar.circle': 'event',
  'calendar.circle.fill': 'event',
  clock: 'access-time',
  'clock.fill': 'access-time',
  timer: 'timer',
  stopwatch: 'timer',
  'stopwatch.fill': 'timer',
  bell: 'notifications',
  'bell.fill': 'notifications',
  'bell.slash': 'notifications-off',
  'bell.slash.fill': 'notifications-off',
  lock: 'lock',
  'lock.fill': 'lock',
  'lock.open': 'lock-open',
  'lock.open.fill': 'lock-open',
  'lock.shield': 'security',
  'lock.shield.fill': 'security',
  key: 'vpn-key',
  'key.fill': 'vpn-key',

  // Text & Formatting
  textformat: 'format-size',
  'textformat.size': 'format-size',
  'textformat.alt': 'text-fields',
  bold: 'format-bold',
  italic: 'format-italic',
  underline: 'format-underlined',
  strikethrough: 'format-strikethrough',
  'list.bullet': 'format-list-bulleted',
  'list.number': 'format-list-numbered',
  'text.alignleft': 'format-align-left',
  'text.aligncenter': 'format-align-center',
  'text.alignright': 'format-align-right',
  quote: 'format-quote',

  // Documents & Files
  doc: 'description',
  'doc.fill': 'description',
  'doc.text': 'article',
  'doc.text.fill': 'article',
  'doc.richtext': 'text-snippet',
  'doc.richtext.fill': 'text-snippet',
  folder: 'folder',
  'folder.fill': 'folder',
  'folder.badge.plus': 'create-new-folder',
  'archivebox.fill': 'archive',
  archivebox: 'archive',
  'tray.fill': 'inbox',
  tray: 'inbox',

  // Device & System
  gear: 'settings',
  'gear.circle': 'settings',
  'gear.circle.fill': 'settings',
  'slider.horizontal.3': 'tune',
  'switch.2': 'toggle-on',
  switch: 'toggle-off',
  'cpu.fill': 'memory',
  cpu: 'memory',
  'externaldrive.fill': 'storage',
  externaldrive: 'storage',
  server: 'dns',
  'server.rack': 'dns',
  wifi: 'wifi',
  'wifi.slash': 'wifi-off',
  'antenna.radiowaves.left.and.right': 'cell-tower',
  'network.badge.shield.half.filled': 'security',

  // Weather & Nature
  sun: 'wb-sunny',
  'sun.max': 'wb-sunny',
  'sun.max.fill': 'wb-sunny',
  moon: 'dark-mode',
  'moon.fill': 'dark-mode',
  'moon.stars': 'bedtime',
  'moon.stars.fill': 'bedtime',
  cloud: 'cloud',
  'cloud.fill': 'cloud',
  'cloud.rain': 'cloud',
  'cloud.rain.fill': 'cloud',
  'cloud.snow': 'ac-unit',
  'cloud.snow.fill': 'ac-unit',
  wind: 'air',
  'thermometer.sun': 'thermostat',
  snowflake: 'ac-unit',

  // Transportation
  car: 'directions-car',
  'car.fill': 'directions-car',
  'car.2': 'directions-car',
  'car.2.fill': 'directions-car',
  bus: 'directions-bus',
  'bus.fill': 'directions-bus',
  tram: 'tram',
  'tram.fill': 'tram',
  bicycle: 'directions-bike',
  airplane: 'flight',
  'airplane.departure': 'flight-takeoff',
  'airplane.arrival': 'flight-land',
  'ferry.fill': 'directions-boat',
  ferry: 'directions-boat',

  // Shopping & Finance
  creditcard: 'credit-card',
  'creditcard.fill': 'credit-card',
  'banknote.fill': 'attach-money',
  banknote: 'attach-money',
  'dollarsign.circle': 'monetization-on',
  'dollarsign.circle.fill': 'monetization-on',
  'cart.fill': 'shopping-cart',
  cart: 'shopping-cart',
  'bag.fill': 'shopping-bag',
  bag: 'shopping-bag',
  gift: 'card-giftcard',
  'gift.fill': 'card-giftcard',
  tag: 'local-offer',
  'tag.fill': 'local-offer',

  // Communication & Network
  globe: 'language',
  'globe.americas': 'public',
  'globe.americas.fill': 'public',
  'globe.europe.africa': 'public',
  'globe.europe.africa.fill': 'public',
  'globe.asia.australia': 'public',
  'globe.asia.australia.fill': 'public',
  'antenna.radiowaves.left.and.right.circle': 'wifi',
  'antenna.radiowaves.left.and.right.circle.fill': 'wifi',
  message: 'message',
  'message.fill': 'message',
  'message.circle': 'chat',
  'message.circle.fill': 'chat',
  'bubble.left': 'chat-bubble-outline',
  'bubble.left.fill': 'chat-bubble',
  'bubble.right': 'chat-bubble-outline',
  'bubble.right.fill': 'chat-bubble',

  // Health & Fitness
  'heart.circle': 'favorite-border',
  'heart.circle.fill': 'favorite',
  'heart.text.square': 'health-and-safety',
  'heart.text.square.fill': 'health-and-safety',
  'figure.walk': 'directions-walk',
  'figure.run': 'directions-run',
  dumbbell: 'fitness-center',
  'dumbbell.fill': 'fitness-center',

  // Entertainment & Gaming
  gamecontroller: 'sports-esports',
  'gamecontroller.fill': 'sports-esports',
  'dice.fill': 'casino',
  dice: 'casino',
  'music.note': 'music-note',
  'music.note.list': 'queue-music',
  'tv.fill': 'tv',
  tv: 'tv',
  'photo.tv': 'live-tv',

  // Camera & Photos
  camera: 'camera',
  'camera.fill': 'camera',
  'camera.circle': 'camera-alt',
  'camera.circle.fill': 'camera-alt',
  photo: 'photo',
  'photo.fill': 'photo',
  'photo.on.rectangle': 'photo-library',
  'photo.on.rectangle.fill': 'photo-library',
  'photo.stack': 'photo-library',
  'photo.stack.fill': 'photo-library',
  'square.stack': 'dynamic-feed',
  'square.stack.fill': 'dynamic-feed',
  film: 'movie',
  'film.fill': 'movie',
  'video.circle': 'videocam',
  'video.circle.fill': 'videocam',

  // Location & Maps
  location: 'location-on',
  'location.fill': 'location-on',
  'location.circle': 'my-location',
  'location.circle.fill': 'my-location',
  'location.north': 'navigation',
  'location.north.fill': 'navigation',
  'location.slash': 'location-off',
  'location.slash.fill': 'location-off',
  map: 'map',
  'map.fill': 'map',
  'mappin.circle': 'place',
  'mappin.circle.fill': 'place',
  'mappin.and.ellipse': 'place',

  // Science & Education
  book: 'menu-book',
  'book.fill': 'menu-book',
  'book.closed': 'book',
  'book.closed.fill': 'book',
  'graduationcap.fill': 'school',
  graduationcap: 'school',
  'studentdesk.fill': 'school',
  studentdesk: 'school',
  'flask.fill': 'science',
  flask: 'science',
  atom: 'biotech',
  'function.fill': 'functions',
  function: 'functions',

  // Business & Work
  building: 'business',
  'building.fill': 'business',
  'building.2': 'domain',
  'building.2.fill': 'domain',
  'briefcase.fill': 'work',
  briefcase: 'work',
  'chart.bar': 'bar-chart',
  'chart.bar.fill': 'bar-chart',
  'chart.pie': 'pie-chart',
  'chart.pie.fill': 'pie-chart',
  'chart.line.uptrend.xyaxis': 'trending-up',
  'percent.fill': 'percent',
  percent: 'percent',

  // Security & Verification
  'checkmark.seal': 'verified',
  'checkmark.seal.fill': 'verified',
  'xmark.seal': 'gpp-bad',
  'xmark.seal.fill': 'gpp-bad',
  'exclamationmark.triangle': 'warning',
  'exclamationmark.triangle.fill': 'warning',
  'exclamationmark.circle': 'error',
  'exclamationmark.circle.fill': 'error',
  'questionmark.circle': 'help',
  'questionmark.circle.fill': 'help',
  'info.circle': 'info',
  'info.circle.fill': 'info',

  // Productivity & Office
  'pencil.and.outline': 'edit-note',
  'square.and.pencil': 'edit',
  'pencil.tip': 'draw',
  'pencil.tip.crop.circle': 'draw',
  highlighter: 'highlight',
  'paintbrush.fill': 'brush',
  paintbrush: 'brush',
  'scissors.fill': 'content-cut',
  scissors: 'content-cut',
  'paperclip.fill': 'attach-file',
  paperclip: 'attach-file',
  'link.fill': 'link',
  link: 'link',

  // Development & Code
  'chevron.left.forwardslash.chevron.right': 'code',
  'curlybraces.square': 'data-object',
  'curlybraces.square.fill': 'data-object',
  'terminal.fill': 'terminal',
  terminal: 'terminal',
  'hammer.fill': 'build',
  hammer: 'build',
  'wrench.fill': 'build',
  wrench: 'build',
  'screwdriver.fill': 'build',
  screwdriver: 'build',

  // Audio & Sound
  waveform: 'graphic-eq',
  'waveform.path': 'equalizer',
  'waveform.circle': 'graphic-eq',
  'waveform.circle.fill': 'graphic-eq',
  'music.quarternote.3': 'library-music',
  'beats.headphones': 'headphones',
  'beats.earphones': 'earbuds',
  'hifispeaker.fill': 'speaker',
  hifispeaker: 'speaker',

  // Power & Battery
  'battery.100': 'battery-full',
  'battery.75': 'battery-6-bar',
  'battery.50': 'battery-4-bar',
  'battery.25': 'battery-2-bar',
  'battery.0': 'battery-alert',
  'bolt.fill': 'flash-on',
  bolt: 'flash-on',
  'bolt.circle': 'flash-on',
  'bolt.circle.fill': 'flash-on',
  'power.fill': 'power-settings-new',
  power: 'power-settings-new',
} as Partial<
  Record<
    import('expo-symbols').SymbolViewProps['name'],
    React.ComponentProps<typeof MaterialIcons>['name']
  >
>;

/**
 * An icon component that uses native SFSymbols on iOS, and MaterialIcons on Android and web. This ensures a consistent look across platforms, and optimal resource usage.
 *
 * Icon `name`s are based on SFSymbols and require manual mapping to MaterialIcons.
 */
export const IconSymbol = memo(function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
});

IconSymbol.displayName = 'IconSymbol';
